all:
	g++ server.cpp -g -rdynamic -o server
	g++ client.cpp -g -rdynamic -o client
server:
	g++ server.cpp -g -rdynamic -o server
client:
	g++ client.cpp -g -rdynamic -o client
clean:
	rm server;rm client
